//Each new term in the Fibonacci sequence is generated by adding the 
//previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not
//exceed four million, find the sum of the even-valued terms.


public class main {
	
	public static int fibonacci(int n)  {
	    if(n == 0)
	        return 0;
	    else if(n == 1)
	      return 1;
	   else
	      return fibonacci(n - 1) + fibonacci(n - 2);
	}
	
	public static void main(String[] args) {
		
		int sum = 0;
	
		for(int i = 0; i<=4000000;i++){
			int a = fibonacci(i);	
			
			if(a>4000000)
				break;
			
			if(a%2 == 0)
				sum += a;
		}
		System.out.print(sum);
		
		
		
	}
}
		


